services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_product
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  ms-product:
    image: ms-product:latest
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    environment:
      PORT: 9090
    networks:
      - my-network

networks:
  my-network:
    driver: bridge