spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://mysql:3306/ms_product
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 9090
  error:
    include-messages: always

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.example.product
  pathsToMatch: /**
api:
  responseCodes:
    ok.description : OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    internalServer.description: Internal Server Error. Seee response message for more information
